'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Feedback

    Partial Public Class CommentSettings

        '''<summary>
        '''valSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''plScope control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plScope As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblScope control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblScope As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''divFeedbackModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divFeedbackModules As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plFeedbackModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFeedbackModules As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''gvFeedbackModules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvFeedbackModules As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''divCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divCategories As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategories As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cblCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cblCategories As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''plHeaderTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHeaderTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtHeaderTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHeaderTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdLoadDefaultHeaderTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLoadDefaultHeaderTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plItemTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItemTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtItemTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdLoadDefaultItemTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLoadDefaultItemTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plAltItemTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAltItemTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAltItemTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAltItemTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdLoadDefAltItemTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLoadDefAltItemTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plSeparatorTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSeparatorTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSeparatorTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSeparatorTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdLoadDefaultSeparatorTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLoadDefaultSeparatorTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plFooterTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFooterTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtFooterTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFooterTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdLoadDefaultFooterTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdLoadDefaultFooterTemplate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plAvailableTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAvailableTokens As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblAvailableTokens control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAvailableTokens As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plEnablePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnablePager As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnablePager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnablePager As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plDefaultPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultPageSize As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtDefaultPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDefaultPageSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDefaultPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDefaultPageSize As Global.System.Web.UI.WebControls.RangeValidator
    End Class
End Namespace
