'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Feedback

    Partial Public Class FeedbackLists

        '''<summary>
        '''plListType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plListType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rbListType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbListType As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''dgItems control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgItems As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''plListName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plListName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtListID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtListID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtBoxListName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBoxListName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valtxtBoxListName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valtxtBoxListName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plListValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plListValue As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtBoxListValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBoxListValue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valtxtBoxListValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valtxtBoxListValue As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plIsActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIsActive As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''checkBoxIsActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents checkBoxIsActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plPortal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPortal As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtModuleID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtModuleID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''checkBoxPortal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents checkBoxPortal As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divErrorRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divErrorRow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plErrorMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plErrorMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdSaveEntry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSaveEntry As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdReturn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
