'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Feedback
    
    Partial Public Class Feedback
        
        '''<summary>
        '''divFeedbackForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divFeedbackForm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''divFeedbackFormContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divFeedbackFormContent As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''valSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSummary As Global.System.Web.UI.WebControls.ValidationSummary
        
        '''<summary>
        '''hContactInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hContactInfo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''divEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmail As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valEmail1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail1 As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''valEmail2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmail2 As Global.System.Web.UI.WebControls.RegularExpressionValidator
        
        '''<summary>
        '''divEmailConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailConfirm As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plEmailConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailConfirm As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtEmailConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailConfirm As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valEmailConfirm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailConfirm As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''valEmailConfirm2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailConfirm2 As Global.System.Web.UI.WebControls.CompareValidator
        
        '''<summary>
        '''divName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divName As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plName As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valName As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''divStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divStreet As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStreet As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStreet As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valStreet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valStreet As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''divCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divCity As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCity As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valCity control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCity As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''divRegion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divRegion As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plRegion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRegion As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtRegion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegion As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valRegion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRegion As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''divCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divCountry As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCountry As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCountry As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCountry As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''divPostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPostalCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plPostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPostalCode As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtPostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostalCode As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valPostalCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPostalCode As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''valPostalCode2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPostalCode2 As Global.System.Web.UI.WebControls.RegularExpressionValidator
        
        '''<summary>
        '''divTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTelephone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTelephone As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTelephone As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valTelephone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTelephone As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''valTelephone2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTelephone2 As Global.System.Web.UI.WebControls.RegularExpressionValidator
        
        '''<summary>
        '''hFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hFeedback As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''divCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divCategory As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategory As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''cboCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboCategory As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''valCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCategory As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''divSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSubject As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubject As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''cboSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSubject As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''valSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSubject As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''divSubject2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSubject2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plSubject2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubject2 As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtSubject2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubject2 As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valSubject2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSubject2 As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''divMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMessage As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''txtBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBody As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''valMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMessage As Global.System.Web.UI.WebControls.RequiredFieldValidator
        
        '''<summary>
        '''valMessageLength control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMessageLength As Global.System.Web.UI.WebControls.RegularExpressionValidator
        
        '''<summary>
        '''plCharCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCharCount As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''CharCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CharCount As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''divFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divFooter As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''divCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divCopy As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCopy As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''chkCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCopy As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''valCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCopy As Global.System.Web.UI.WebControls.CustomValidator
        
        '''<summary>
        '''divCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divCaptcha As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''plCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptcha As Global.System.Web.UI.UserControl
        
        '''<summary>
        '''ctlCaptcha control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlCaptcha As Global.DotNetNuke.Web.UI.WebControls.DnnCaptcha
        
        '''<summary>
        '''cmdSend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSend As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''divConfirmation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divConfirmation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''divResponseMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divResponseMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
