'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Feedback

    Partial Public Class Moderation

        '''<summary>
        '''cbShowOnlyModeratedCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbShowOnlyModeratedCategories As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dgPendingFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgPendingFeedback As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pgPendingFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pgPendingFeedback As Global.DotNetNuke.UI.WebControls.PagingControl

        '''<summary>
        '''dgPrivateFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgPrivateFeedback As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pgPrivateFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pgPrivateFeedback As Global.DotNetNuke.UI.WebControls.PagingControl

        '''<summary>
        '''dgPublicFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgPublicFeedback As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pgPublicFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pgPublicFeedback As Global.DotNetNuke.UI.WebControls.PagingControl

        '''<summary>
        '''dgArchiveFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgArchiveFeedback As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pgArchiveFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pgArchiveFeedback As Global.DotNetNuke.UI.WebControls.PagingControl

        '''<summary>
        '''pnlSpam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSpam As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dgSpamFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgSpamFeedback As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pgSpamFeedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pgSpamFeedback As Global.DotNetNuke.UI.WebControls.PagingControl

        '''<summary>
        '''cmdReturn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
