'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Feedback

    Partial Public Class Settings

        '''<summary>
        '''valSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''plSendTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSendTo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSendTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSendTo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valSendTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSendTo As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plSendToRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSendToRoles As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''dgSelectedRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgSelectedRoles As Global.DotNetNuke.UI.WebControls.RolesSelectionGrid

        '''<summary>
        '''plSendFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSendFrom As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSendFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSendFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valSendFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSendFrom As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plSendCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSendCopy As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSendCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSendCopy As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plOptout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOptout As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkOptout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOptout As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAsync control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAsync As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAsync control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAsync As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategory As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plCategorySelectable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategorySelectable As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCategory As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''valCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCategory As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''plCategoryReq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategoryReq As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCategoryReq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCategoryReq As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plUseCategoryAsEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUseCategoryAsEmail As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCategoryMailto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCategoryMailto As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''valCategoryMailto control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valCategoryMailto As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''plLabelDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLabelDisplay As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblLabelDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblLabelDisplay As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plWidth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valWidth As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cboSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSubject As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSubjectEditField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubjectEditField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblSubjectEditField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblSubjectEditField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plEmailField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblEmailField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblEmailField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plEmailConfirmField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailConfirmField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblEmailConfirmField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblEmailConfirmField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plNameField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNameField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblNameField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblNameField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plStreetField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStreetField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblStreetField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblStreetField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plCityField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCityField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblCityField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblCityField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plRegionField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRegionField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblRegionField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRegionField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plCountryField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCountryField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblCountryField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblCountryField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plPostalCodeField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPostalCodeField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblPostalCodeField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblPostalCodeField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plTelephoneField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTelephoneField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblTelephoneField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblTelephoneField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plMessageField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMessageField As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblMessageField control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblMessageField As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plEmailRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailRegex As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailRegex As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnResetEmailRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnResetEmailRegex As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''valEmailRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailRegex As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plPostalCodeRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPostalCodeRegex As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPostalCodeRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostalCodeRegex As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnResetPostalCodeRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnResetPostalCodeRegex As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''plTelephoneRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTelephoneRegex As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTelephoneRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTelephoneRegex As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnResetTelephoneRegex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnResetTelephoneRegex As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''plRows control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRows As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtrows control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtrows As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valRows control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valRows As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plMaxMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaxMessage As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMaxMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxMessage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaxMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxMessage As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plCaptchaVisibility control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptchaVisibility As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblCaptchaVisibility control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblCaptchaVisibility As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plCaptchaAudio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptchaAudio As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCaptchaAudio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCaptchaAudio As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCaptchaCase control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptchaCase As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCaptchaCase control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCaptchaCase As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCaptchaLineNoise control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptchaLineNoise As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlCaptchaLineNoise control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCaptchaLineNoise As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plCaptchaBackgroundNoise control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCaptchaBackgroundNoise As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlCaptchaBackgroundNoise control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCaptchaBackgroundNoise As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plRepeatSubmissionFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRepeatSubmissionFilter As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblRepeatSubmissionFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblRepeatSubmissionFilter As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plMinSubmissionInteval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMinSubmissionInteval As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMinSubmissionInteval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMinSubmissionInteval As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMinSubmissionInteval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMinSubmissionInteval As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plDuplicateSubmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDuplicateSubmission As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkDuplicateSubmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDuplicateSubmission As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plRedirectTabOnSubmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRedirectTabOnSubmission As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlRedirectTabOnSubmission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRedirectTabOnSubmission As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plAkismetEnable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAkismetEnable As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAkismetEnable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAkismetEnable As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAkismetKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAkismetKey As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAkismetKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAkismetKey As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAkismetKey control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAkismetKey As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''plAkismetSendModerator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAkismetSendModerator As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAkismetSendModerator control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAkismetSendModerator As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plScope control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plScope As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblScope control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblScope As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''divOrphanedData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divOrphanedData As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plOrphanedData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOrphanedData As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''dgOrphanedData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgOrphanedData As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''cmdDeleteOrphanedData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDeleteOrphanedData As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''plModerated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModerated As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkModerated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkModerated As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plModerationAdminEmails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModerationAdminEmails As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkModerationAdminEmails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkModerationAdminEmails As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEmailOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailOnly As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailOnly As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEmailOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEmailOnly As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divSendWhenPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSendWhenPublished As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plSendWhenPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSendWhenPublished As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkSendWhenPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSendWhenPublished As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divModerationCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divModerationCategories As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plModerationCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModerationCategory As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cblModerationCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cblModerationCategories As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''divUnmoderatedStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUnmoderatedStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plUnmoderatedStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUnmoderatedStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlUnmoderatedStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlUnmoderatedStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plPrintTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPrintTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPrintTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPrintTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnLoadDefaultPrintTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLoadDefaultPrintTemplate As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''plPrintAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPrintAction As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rblPrintAction control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblPrintAction As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plModerationPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModerationPageSize As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlModerationPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlModerationPageSize As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plCleanupPending control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCleanupPending As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCleanupPending control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCleanupPending As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCleanupPrivate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCleanupPrivate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCleanupPrivate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCleanupPrivate As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCleanupPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCleanupPublished As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCleanupPublished control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCleanupPublished As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCleanupArchived control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCleanupArchived As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCleanupArchived control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCleanupArchived As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCleanupSpam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCleanupSpam As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkCleanupSpam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCleanupSpam As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCleanupDaysBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCleanupDaysBefore As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCleanupDaysBefore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCleanupDaysBefore As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Regularexpressionvalidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Regularexpressionvalidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plCleanupMaxEntries control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCleanupMaxEntries As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCleanupMaxEntries control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCleanupMaxEntries As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Regularexpressionvalidator2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Regularexpressionvalidator2 As Global.System.Web.UI.WebControls.RegularExpressionValidator
    End Class
End Namespace
